Added some solutions
DanielSank/vankampen-stochastic pull request #10
Opened 2017-01-15 19:55 UTC by Edlingeer

2017-01-16 18:55 UTC, DanielSank commented
Thank you! I might not get around to this until the weekend, but in any case the contribution is very much appreciated.

2017-02-27 03:34 UTC, DanielSank commented
I'm finally returning to this project. Yay. Should have this merged soon.

2017-03-06 01:30 UTC, DanielSank commented on .gitignore
> +main.toc
FWIW I set my latex system to put built files in a `build/` directory (hence the top line of this file). No problem adding the other lines too, for folks who build in-place.

2017-03-06 08:39 UTC, DanielSank requested changes
Thanks, this is great. There are a couple of little punctuation errors. If you can fix them up I'll merge this.

2017-03-06 08:39 UTC, DanielSank commented on chapter2/Description_sequence_random_events.tex
> +We need to find a description of a sequence of random events at $\tau_1$, $\tau_2$, ... in terms of the probability distribution $Q_s$ using the probability $w$. The $w$ probability is the simplest d
There are a few punctuation errors here, i.e. a space missing at the end of a sentence, etc.

2017-03-06 08:39 UTC, DanielSank commented on chapter2/Mean_square_N_interval.tex
> +in the end we can rewrite $\langle N^2 \rangle$
Capitalize beginning of new sentence?

2017-03-06 08:39 UTC, DanielSank commented on chapter2/Description_sequence_random_events.tex
> +& P(\tau_s)=  \int_{0}^{\tau_s}w(\tau_s-\tau_{s-1})d\tau_{s-1}\\
Just FYI, in TeX you can do, for example, `\int_0^\infty`, i.e. you don't need braces in superscripts and subscripts if there's only one symbol.

2017-03-06 08:45 UTC, Edlingeer commented
Hi,

No problem, I'll fix this after work today. And thanks for the feedback.

--
Thomas

--
Thomas

2017-03-06 9:39 GMT+01:00 Daniel Sank <notifications@github.com>:

> *@DanielSank* requested changes on this pull request.
>
> Thanks, this is great. There are a couple of little punctuation errors. If
> you can fix them up I'll merge this.
> ------------------------------
>
> In chapter2/Description_sequence_random_events.tex
> <https://github.com/DanielSank/vankampen-stochastic/pull/10#discussion_r104363415>
> :
>
> > @@ -0,0 +1,24 @@
> +\leveldown{Description of a sequence of random events - pg. 32}
> +
> +\leveldown{Problem}
> +
> +Calculate $Q_s$ for the given recipe of construction of a random set of dots
> +\levelstay{Solution}
> +We need to find a description of a sequence of random events at $\tau_1$, $\tau_2$, ... in terms of the probability distribution $Q_s$ using the probability $w$. The $w$ probability is the simplest description of correlated random events : the new arrival is dependent on the timing from the previous arrival and both arrivals are governed by the same probability function $w$. We may as well represent this situation by having $s$ replicas of the system and reporting the first random events in each of these systems.Such first event would be governed by a probability $w$. We can write $Q_s$ as a probability of events that are independent of one another in each of these systems.
>
> There are a few punctuation errors here, i.e. a space missing at the end
> of a sentence, etc.
> ------------------------------
>
> In chapter2/Mean_square_N_interval.tex
> <https://github.com/DanielSank/vankampen-stochastic/pull/10#discussion_r104363609>
> :
>
> > +\begin{equation}
> +\begin{split}
> +& \int_{-\infty}^{\infty}\chi^2(\tau_i)Q_s(\tau_1,\tau_2,...,\tau_i,...,\tau_s)d\tau_1d\tau_2...d\tau_s\\
> +& \Leftrightarrow \int_{-\infty}^{\infty}\chi^2(\tau_i)Q_s(\tau_i,\tau_2,...,\tau_1,...,\tau_s)d\tau_1d\tau_2...d\tau_s \\
> +& \Leftrightarrow \int_{-\infty}^{\infty}\chi^2(\tau_1)Q_s(\tau_1,\tau_2,...,\tau_i,...,\tau_s)d\tau_id\tau_2...d\tau_1...d\tau_s \\
> +& \Leftrightarrow\int_{t_a}^{t_b}\left[d\tau_1 \int_{-\infty}^{\infty}Q_s(\tau_1,...,\tau_s)d\tau_2...d\tau_s \right]
> +\end{split}
> +\end{equation}
> +in the same fashion we can transform the expression $(b)$ getting the following result
> +\begin{equation}
> +\begin{split}
> +& \int_{-\infty}^{\infty}\chi(\tau_i)\chi(\tau_j)Q_s(\tau_1,\tau_2,...,\tau_s)d\tau_1d\tau_2...d\tau_s \\
> +& \Leftrightarrow \int_{t_a}^{t_b}\left[d\tau_1\int_{t_a}^{t_b}d\tau_2\int_{-\infty}^{\infty}Q_s(\tau_1,\tau_2,...,\tau_s)d\tau_3...d\tau_s\right] \\
> +\end{split}
> +\end{equation}
> +in the end we can rewrite $\langle N^2 \rangle$
>
> Capitalize beginning of new sentence?
> ------------------------------
>
> In chapter2/Description_sequence_random_events.tex
> <https://github.com/DanielSank/vankampen-stochastic/pull/10#discussion_r104363908>
> :
>
> > +\leveldown{Problem}
> +
> +Calculate $Q_s$ for the given recipe of construction of a random set of dots
> +\levelstay{Solution}
> +We need to find a description of a sequence of random events at $\tau_1$, $\tau_2$, ... in terms of the probability distribution $Q_s$ using the probability $w$. The $w$ probability is the simplest description of correlated random events : the new arrival is dependent on the timing from the previous arrival and both arrivals are governed by the same probability function $w$. We may as well represent this situation by having $s$ replicas of the system and reporting the first random events in each of these systems.Such first event would be governed by a probability $w$. We can write $Q_s$ as a probability of events that are independent of one another in each of these systems.
> +\begin{equation}
> +Q_s(\tau_1, \tau_2,...,\tau_s)=P(\tau_1)P(\tau_2)...P(\tau_s)
> +\end{equation}
> +Thus we have
> +\begin{equation}
> +\begin{split}
> +& P(\tau_1)= w(\tau_1) \\
> +& P(\tau_2)= \int_{0}^{\tau_2}w(\tau_2-\tau_1)d\tau_1\\
> +& P(\tau_3)=  \int_{0}^{\tau_3}w(\tau_3-\tau_2)d\tau_2\\
> +& ... \\
> +& P(\tau_s)=  \int_{0}^{\tau_s}w(\tau_s-\tau_{s-1})d\tau_{s-1}\\
>
> Just FYI, in TeX you can do, for example, \int_0^\infty, i.e. you don't
> need braces in superscripts and subscripts if there's only one symbol.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DanielSank/vankampen-stochastic/pull/10#pullrequestreview-25195560>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AD1Tokr079lGvTq6WnyQVuBmyWWzlVKhks5ri8YogaJpZM4LkA2e>
> .
>

2017-03-11 10:53 UTC, Edlingeer commented
I made some changes as you asked. Is it okay now ? sorry for the time it took me to get to this, I had some unexpected last minutes things that came up.

2017-12-02 00:06 UTC, DanielSank commented
Woah, I'm sorry I forgot about this. I'll try to look at it this weekend.

2024-09-02 20:22 UTC, DanielSank submitted a review, later dismissed
Thanks for your contribution. I'm merging as is and will make a follow-up commit to make this new content adhere to the style guide.

2024-09-02 20:24 UTC, DanielSank approved these changes

2024-09-02 20:25 UTC, merged